cs3216-a3-group-4/assignment-3

.github/workflows/deploy.yml, .github/workflows/lint.yml
https://stackoverflow.com/questions/67132301/command-not-found-when-sshing-into-server-via-non-interactive-session
=> ci: attempt to fix deployment

backend/src/auth/router.py, frontend/app/auth/google/page.tsx, frontend/components/miscellaneous/google-oauth-button.tsx, frontend/components/ui/loading-spinner.tsx
=> fix: attempt to fix oauth flow

frontend/app/login/page.tsx, frontend/app/register/page.tsx
=> fix: save cookies

backend/src/events/models.py, backend/src/scripts/seed.py
article can have many events
also add seed for categories (with scuffed association example)
=> fix: event association in article

frontend/app/(authenticated)/user/profile/category-form.tsx
update user store categories in store
=> fix: category form

frontend/app/(authenticated)/categories/[id]/page.tsx, frontend/app/_home/date-range-selector.tsx, frontend/app/_home/events-list.tsx, frontend/app/_home/home.tsx, frontend/app/home.tsx, frontend/app/page.tsx, frontend/components/navigation/pagination.tsx, frontend/hooks/use-pagination.ts, frontend/queries/event.ts, frontend/utils/date.ts, frontend/utils/string.ts
- adds pagination to home screen
- refactors home screen event fetching to use react-query
- refactors pagination into hook + component
- fixes bugs on 0 items + 0 pages + < 2 pages
fixes #144 , #118
=> feat: home pagination

frontend/app/(authenticated)/events/[id]/event-analysis.tsx
=> fix: fix event tab ordering

backend/src/notes/router.py, backend/src/notes/schemas.py, frontend/app/(authenticated)/events/[id]/event-notes.tsx, frontend/app/(authenticated)/events/[id]/note-form.tsx, frontend/app/(authenticated)/events/[id]/page.tsx, frontend/client/schemas.gen.ts, frontend/client/types.gen.ts, frontend/queries/note.ts
i know it looks atrocious, but i have been told to throw for the frontend so i have banned myself from using "className" unless i am copy pasting it from somewhere else
partially unblocks #134 for @chloeelim 
closes #138
=> feat: add event notes

frontend/app/(authenticated)/events/[id]/event-analysis.tsx, frontend/queries/note.ts
had to use one css class for highlight, rip
other than that, mostly follows the dont care about css order
https://github.com/user-attachments/assets/05b7b488-20b2-4cf3-aa17-8497562b9e7c
unblocks #134 @chloeelim 
closes #137
=> feat: init frontend notes

frontend/app/(authenticated)/answers/[id]/page.tsx
=> fix(answer-page): scroll to top

frontend/app/(authenticated)/events/[id]/event-analysis.tsx
=> fix(highlight): span multiple spans

frontend/app/landing.tsx, frontend/components/auth/user-profile-button.tsx, frontend/components/navigation/mobile/mobile-sidebar.tsx, frontend/components/navigation/sidebar/sidebar-item-with-icon.tsx, frontend/components/navigation/sidebar/sidebar-topics.tsx, frontend/components/navigation/sidebar/sidebar.tsx, frontend/package-lock.json, frontend/package.json
also removes unused library react-ga4
=> refactor: router push on click => Link component

backend/src/notes/router.py, backend/src/notes/schemas.py, frontend/app/(authenticated)/events/[id]/event-analysis.tsx, frontend/app/(authenticated)/events/[id]/note-form.tsx, frontend/client/schemas.gen.ts, frontend/client/types.gen.ts, frontend/queries/note.ts
- show selected portion
- tiny button to add annotation to open form
- deactivate form/selection on successful add
=> fix(highlighting): improve many things

frontend/components/navigation/pagination.tsx
=> feat(pagination): show page count + input to edit

backend/src/embeddings/vector_store.py, backend/src/lm/generate_points.py, backend/src/lm/generate_response.py, backend/src/user_questions/router.py
use async api for llm
make vector store query async
remove n+1 bottleneck when querying events
52s -> 9s
=> fix(user-question): optimise

backend/src/events/dependencies.py, backend/src/events/router.py, frontend/app/(authenticated)/events/[id]/page.tsx, frontend/queries/event.ts, frontend/queries/note.ts
=> feat(event): add read event to frontend

frontend/components/layout/app-layout.tsx
=> fix(app-layout): fix loading indicator in suspense

frontend/app/_home/date-range-selector.tsx, frontend/app/_home/home.tsx, frontend/queries/user.ts
=> fix(home): make time selector work and mobile responsive

frontend/components/navigation/mobile/mobile-navbar.tsx, frontend/components/navigation/mobile/mobile-sidebar.tsx, frontend/components/navigation/navbar.tsx, frontend/components/navigation/sidebar/sidebar-topics.tsx, frontend/tailwind.config.ts
=> feat: add hamburger menu

backend/src/app.py, backend/src/auth/dependencies.py
=> fix(auth): protect all routes

frontend/app/(authenticated)/bookmarks/page.tsx, frontend/app/(authenticated)/events/[id]/event-analysis.tsx, frontend/app/(authenticated)/events/[id]/event-notes.tsx, frontend/app/(authenticated)/events/[id]/note-form.tsx, frontend/app/(authenticated)/notes/[id]/page.tsx, frontend/client/types.gen.ts, frontend/components/navigation/mobile/mobile-sidebar.tsx, frontend/components/notes/note-dialog-content.tsx, frontend/components/notes/note.tsx, frontend/queries/note.ts
Improvements:
-Remove console.log left behind on frontend
-Improve efficiency of bookmarks page, thus fixing an React warning
-Determine Category for event analysis notes and insert it into backend when adding such a note
-Handle null category ID for notes fetched from backend and display them nicely on the frontend without error
=> Fix some bugs

frontend/app/(authenticated)/template.tsx, frontend/components/layout/app-layout.tsx, frontend/components/navigation/mobile/mobile-navbar.tsx, frontend/components/navigation/navbar.tsx, frontend/store/user/user-store.ts
related to #187 
idk if this breaks anything else, and it is also likely not optimal
=> (fix): session expire

frontend/app/(authenticated)/events/[id]/event-annotations/analysis-fragment.tsx
proposal on highlight deselect regression, adding a close option to actions
=> feat: highlight close

frontend/app/(authenticated)/events/[id]/event-analysis.tsx, frontend/app/(authenticated)/events/[id]/event-annotations/analysis-fragment.tsx, frontend/app/(authenticated)/events/[id]/page.tsx, frontend/app/landing.tsx, frontend/components/layout/app-layout.tsx, frontend/components/layout/content-layout.tsx, frontend/components/navigation/mobile/mobile-navbar.tsx, frontend/components/navigation/navbar.tsx
cc @chloeelim 
- use css to disable text selection if form not displayed + there is a highlight
- on highlight + form displayed + click text = disable form display and remove highlight.
=> fix: highlights on mobile

frontend/package-lock.json, frontend/package.json
closes: #214 
caused by a react-select bug fixed in version 2.1.2, see https://github.com/radix-ui/primitives/issues/1658
=> fix(singapore_filter): bump react-select to 2.1.2

frontend/app/(authenticated)/events/[id]/event-bookmark-button.tsx
=> fix(bookmark): remove extra 0 in toast

frontend/app/(authenticated)/categories/[id]/page.tsx, frontend/app/(authenticated)/events/[id]/page.tsx, frontend/app/_home/home.tsx
=> fix: close notes panel by default if no notes

frontend/app/(authenticated)/ask/ask-page.tsx, frontend/app/(authenticated)/essay-feedback/page.tsx
‘As technological developments become more sophisticated, books play no role in learning.’ How
far is this true of your society?
fails validation (gp sample paper q7)
=> fix: relax character count

backend/src/lm/concept_gen_prompt.py, backend/src/lm/lm_prompt_test.py
* Add sysprompt for concept generation (from article and event title - seems to give most consistent results)
* Add a test script
=> Feat add concept lm generation prompt

backend/src/app.py, backend/src/articles/dependencies.py, backend/src/articles/router.py, backend/src/common/schemas.py, backend/src/events/models.py, backend/src/events/schemas.py, backend/src/lm/generate_concepts.py
=> feat: add article routes

backend/pyproject.toml, backend/uv.lock
we can look into it _when we get the time_ (translation: *never*)
this is just to run the command then laugh at the error count
`cd backend && uv run mypy .`
=> chore: add mypy

backend/src/cron/fetch_articles.py, backend/src/lm/generate_concepts.py
=> chore: deploy (once more)

backend/alembic/versions/c54110455094_add_concept_like.py
-Merge alembic history of main branch with my 'stripe-payment' branch
=> Fix alembic history

backend/alembic/versions/933d84ad4302_add_subscription_table.py, backend/alembic/versions/c54110455094_add_concept_like.py
-Modify alembic history to fix skipped database migrations
=> Fix alembic history again

backend/alembic/versions/5d5b472013f6_add_subscription_and_stripe_session_table.py
Fix alembic downgrade migration
=> Fix alembic downgrade script

frontend/app/(authenticated)/essay-feedback/[id]/page.tsx, frontend/app/(authenticated)/essay-feedback/page.tsx
=> fix: text wrap issue

backend/src/app.py, backend/src/auth/router.py, backend/src/common/constants.py, backend/src/utils/mail.py
=> feat: email jippythefrog@gmail.com on 500

frontend/types/billing.ts
- Remove feature that is yet to be implemented from Jippy feature list
=> Remove non-existent feature

backend/src/lm/evaluate_article.py, backend/src/lm/lm_prompt_test.py
=> fix: useful filter

frontend/app/(authenticated)/home/action-bar-item.tsx, frontend/app/(authenticated)/home/action-bar-mobile.tsx, frontend/app/(authenticated)/home/action-bar.tsx, frontend/app/(authenticated)/home/article-card.tsx, frontend/app/(authenticated)/home/article-feed.tsx, frontend/app/(authenticated)/home/page.tsx, frontend/app/(authenticated)/home/top-article-list.tsx
=> feat: home page refinements

frontend/app/(authenticated)/home/action-bar.tsx, frontend/components/navigation/mobile/mobile-sidebar.tsx, frontend/components/navigation/sidebar/sidebar.tsx
fixes https://github.com/orgs/cs3216-a3-group-4/projects/5/views/1?pane=issue&itemId=85209324&issue=cs3216-a3-group-4%7Cassignment-3%7C338
=> fix: ask-a-question naming -> essay helper

backend/src/lm/generate_concepts.py, backend/src/lm/generate_events.py, backend/src/lm/lm.py
replace while Trues with more robust error handling
=> feat: add error handling for LM loops

backend/src/embeddings/vector_store.py, backend/src/lm/generate_concepts.py, backend/src/lm/generate_events.py, backend/src/lm/lm.py
add some preventive measures for infinite loops
=> chore: redeploy

frontend/app/(authenticated)/user/billing/page.tsx, frontend/app/landing.tsx, frontend/components/billing/pricing-table.tsx, frontend/components/ui/carousel.tsx, frontend/package-lock.json, frontend/package.json
=> Improve layout of some frontend pages

frontend/app/(authenticated)/essay-feedback/page.tsx
- Organise layout of essay feedback page on mobile so it looks more aesthetic
=> Improve mobile layout of essay feedback page

frontend/app/(unauthenticated)/register/page.tsx
someone help do some thing with the green thing
related to #346
=> fix: big screen bug where green part is too small

backend/src/essays/router.py, backend/src/lm/generate_essay_comments.py, frontend/app/(authenticated)/essay-feedback/page.tsx
solves #390 
* parallelized essay grader
=> Fix add validation for essay grader

backend/src/embeddings/store_concepts.py, backend/src/embeddings/vector_store.py, backend/src/essay_helper/generate_concept_response.py, backend/src/lm/dict_types.py, backend/src/lm/generate_essay_comments.py, backend/src/lm/generate_points.py, backend/src/lm/generate_response.py
=> style: use typeddict

backend/src/cron/fetch_articles.py, backend/src/embeddings/store_concepts.py, backend/src/lm/generate_concepts.py
to store concepts in vector db
=> feat: update cron

frontend/app/(authenticated)/user/billing/page.tsx, frontend/types/billing.ts
Update tier IDs to fix handling of Jippy Premium Tier
=> Fix frontend tier handling

backend/src/lm/generate_response.py, backend/src/lm/lm.py
Critical fix for frontend handling of Jippy Tiers, especially Jippy Premium
=> CRITICAL: Merge frontend tier fixes

frontend/app/landing.tsx, frontend/components/landing/faq-answer.tsx, frontend/components/landing/feature-list.tsx, frontend/components/landing/sample-feedback.tsx, frontend/components/landing/sample-points.tsx, frontend/components/news/news-article.tsx, frontend/components/ui/highlight.tsx, frontend/types/landing.ts
New 'Features' section with feature demos:
'Features' section now modified into 'Why Jippy' section, with updated look on desktop(no carousel):
More FAQs and accompanied answers:
=> Better landing page

frontend/app/landing.tsx
Fixes: 
- Fix apostrophe not being rendered due to being encapsulated within a string instead of being passed directly to a component
=> Fix rendering issue
